export namespace zp_GameData {
    export const GameData = {
            betThisRound: 0,
            gameStatus: 0,
            selectIndex: 0,
            allJettonMoney: 0,
            areaBetArray: [{
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }],
            areaItBetArray: [{
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }, {
                areaAllJettonMoney: 0
            }],
            lastAreaBetArray: [],
            allLastMyJettonMoney: 0,
            lastMyAreaBetArray: [],
            getJettonPos: [],
            gameTime: 0,
            userScore: 0
        };

        export let ChipList = [1, 5, 20, 50, 100];

        export const JettonMoney2Index = {
            [ChipList[0]]: 1,
            [ChipList[1]]: 2,
            [ChipList[2]]: 3,
            [ChipList[3]]: 4,
            [ChipList[4]]: 5,
          };

        export let numberFormat = function(e) {
            return {
        value: parseFloat(e).toFixed(2).toString(),
        unit: ""
    };
        }
}